### ISSUE TITLE
Decorations (colgroup) missing initially

### ISSUE THREAD

**Issue by OkanEsen** [massifrg/prosemirror-tables-sections#4]
First, thanks for the plugin, the extensions made to the original `prosemirror-tables` work perfectly.

There is an issue while pasting or loading tables which do have `colgroup` elements though. The original implementation triggered `updateColumnsOnResize` while rendering the NodeView (https://github.com/ProseMirror/prosemirror-tables/blob/master/src/tableview.ts#L19), which added the `colgroup` elements. A similar call seems to be missing for this implementation using decorations.

The decorations and the missing `colgroup` elements are rendered as soon as a resize action is triggered, so the information is obviously there.

**Comment by massifrg** [comment]
Thank you for looking into the code and for your hint on `updateColumnsOnResize`.

I already saw that problem in the main project that provided me the motivation to upgrade the original prosemirror-tables to support table bodies, head and foot (a visual editor for [Pandoc AST](https://hackage.haskell.org/package/pandoc-types-1.23/docs/Text-Pandoc-Definition.html)).

Your hint is precious, because my knowledge of Prosemirror is still a work in progress.

While coding my fork, I was surprised when my changes to the code passed the tests.
Apparently the original code by the author of Prosemirror provided a very solid base to build upon.

Thank you again, I'll see if I can fix this issue.

**Comment by OkanEsen** [comment]
Thanks for looking into the issue!

Unfortunately, I haven't had the time to look into the changes in detail, otherwise I would've tried to come up with a solution to this issue and fix up a PR. Sorry about that!

I'm glad the bug report helps you though, thank you very much for your prompt answer!

**Comment by massifrg** [comment]
I just pushed version 0.6.0, that goes back to the original implementation of column resizing with a custom NodeView.

It seems to work pretty well and it should solve the problem of column widths on creation and pasting.

Could you test it?

**Comment by OkanEsen** [comment]
Sorry for being late and thank you very much for implementing this so quickly.

I was able to test the implementation and it almost seems to work perfectly but I think there is still an issue while parsing the width values (https://github.com/massifrg/prosemirror-tables-sections/blob/main/src/schema.ts#L18-L22).

The problem here is, that tables created outside of ProseMirror won't have the `data-colwidth` attribute, namely width inside the `style` attribute and also the `width` attribute itself.

Example:
```html
<td width='200'>[...]</td>
<td style='width: 200px'>[...]</td>
```

Two things to consider:
1. `data-colwidth`, `width` and also `style='width: 200px'` could exist simultationusly, so maybe some kind of prioritizing of attributes should be made (`data-colwidth` > `width` > `style='width: 200px'`)?
2. The value inside of `style` could be of different units ([absolute](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#absolute_length_units) and [relative](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#relative_length_units)).

**Comment by massifrg** [comment]
In the next release, there will be a `setComputedStyleColumnWidths` command, that modifies the `colwidth` attribute of all the cells of

- the inner table in the selection

- a selection of columns (when the selection covers all the cells of some columns, from the first to the last row)

The command uses [getComputedStyle](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) to compute the width of a cell; so you may specify that with a HTML `width` attribute, a `style` attribute or even an external CSS, as long as `getComputedStyle` takes them into account.

The `colwidth` attr of the cells is then updated to the computed value, so it also ends up in `data-colwidth`.

It's already working here, let me add some documentation before I release it.

**Comment by massifrg** [comment]
Version 0.6.1 is out.

It also adds a `setRelativeColumnWidths(widths: number[], minwidth?: number)` command.

See the [README](https://github.com/massifrg/prosemirror-tables-sections).
